package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Base Islamic Emerald & Gold Palette (Theme 1: الزمردي والذهبي)
val EmeraldPrimaryLight = Color(0xFF0C5E3D)
val EmeraldOnPrimaryLight = Color(0xFFFFFFFF)
val EmeraldPrimaryContainerLight = Color(0xFFD3F8DF)
val EmeraldOnPrimaryContainerLight = Color(0xFF002113)
val GoldSecondaryLight = Color(0xFFB8860B)
val GoldOnSecondaryLight = Color(0xFFFFFFFF)
val GoldSecondaryContainerLight = Color(0xFFFFEFA8)
val GoldOnSecondaryContainerLight = Color(0xFF261A00)
val SandTertiaryLight = Color(0xFF8D5B1E)
val BackgroundLight = Color(0xFFF9F9F6)
val SurfaceLight = Color(0xFFFFFFFF)
val SurfaceVariantLight = Color(0xFFF0EFEA)
val OnSurfaceLight = Color(0xFF1E1E1C)
val OnSurfaceVariantLight = Color(0xFF534F47)
val OutlineLight = Color(0xFF868278)

val EmeraldPrimaryDark = Color(0xFF4EDE9C)
val EmeraldOnPrimaryDark = Color(0xFF003822)
val EmeraldPrimaryContainerDark = Color(0xFF005234)
val EmeraldOnPrimaryContainerDark = Color(0xFFA7F5CA)
val GoldSecondaryDark = Color(0xFFFFD54F)
val GoldOnSecondaryDark = Color(0xFF402D00)
val GoldSecondaryContainerDark = Color(0xFF5C4300)
val GoldOnSecondaryContainerDark = Color(0xFFFFE082)
val SandTertiaryDark = Color(0xFFFFB870)
val BackgroundDark = Color(0xFF111714)
val SurfaceDark = Color(0xFF161F1A)
val SurfaceVariantDark = Color(0xFF233029)
val OnSurfaceDark = Color(0xFFE2EBE5)
val OnSurfaceVariantDark = Color(0xFFC0C9C2)
val OutlineDark = Color(0xFF8A938C)

// Damascus Azure Palette (Theme 2: الأزرق الدمشقي)
val DamascusPrimaryLight = Color(0xFF1B5583)
val DamascusPrimaryDark = Color(0xFF80CAFF)
val DamascusSecondaryLight = Color(0xFFC59434)
val DamascusSecondaryDark = Color(0xFFFFD770)

// Andalusian Terracotta/Ruby Palette (Theme 3: القرمزي الأندلسي)
val AndalusianPrimaryLight = Color(0xFF8C2D2B)
val AndalusianPrimaryDark = Color(0xFFFFB3AD)
val AndalusianSecondaryLight = Color(0xFFB07D38)
val AndalusianSecondaryDark = Color(0xFFFFDB99)

// Seljuk Sapphire Palette (Theme 4: الكحلي السلجوقي)
val SeljukPrimaryLight = Color(0xFF133B5C)
val SeljukPrimaryDark = Color(0xFF70B3E8)
val SeljukSecondaryLight = Color(0xFF00818A)
val SeljukSecondaryDark = Color(0xFF4DE2EC)

// Desert Ochre Palette (Theme 5: الرملي التراثي)
val DesertPrimaryLight = Color(0xFF7A5123)
val DesertPrimaryDark = Color(0xFFFFBA75)
val DesertSecondaryLight = Color(0xFF596328)
val DesertSecondaryDark = Color(0xFFC2D27A)

// Extra Semantic & Islamic Accent Colors
val IslamicGold = Color(0xFFD4AF37)
val IslamicBrightGold = Color(0xFFFFDF73)
val IslamicDarkGreen = Color(0xFF0B462C)
val BattleRed = Color(0xFFC62828)
val VictoryGreen = Color(0xFF2E7D32)
val TreatyBlue = Color(0xFF1565C0)
val ParchmentPaper = Color(0xFFFAF5E9)
val ParchmentDark = Color(0xFF242019)
val CardBorderGold = Color(0x33D4AF37)
val AMOLEDBackground = Color(0xFF000000)
val AMOLEDSurface = Color(0xFF0A0F0D)
